#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WRKDIR = `pwd`
MAKE = make

all: engine_engine robotarm_robotarm unittest_unittest

engine_engine: 
	$(MAKE) -C Engine all -f Engine.cbp.mak

robotarm_robotarm: 
	$(MAKE) -C RobotArm all -f RobotArm.cbp.mak

unittest_unittest: 
	$(MAKE) -C UnitTest all -f UnitTest.cbp.mak

clean: clean_engine_engine clean_robotarm_robotarm clean_unittest_unittest

clean_engine_engine: 
	$(MAKE) -C Engine clean -f Engine.cbp.mak

clean_robotarm_robotarm: 
	$(MAKE) -C RobotArm clean -f RobotArm.cbp.mak

clean_unittest_unittest: 
	$(MAKE) -C UnitTest clean -f UnitTest.cbp.mak

.PHONY: clean_engine_engine clean_robotarm_robotarm clean_unittest_unittest

